VERTEX_SKYBOX = "assets/shaders/skybox.vert"
FRAGMENT_SKYBOX = "assets/shaders/skybox.frag"
VERTEX_FRENCH_FRIES = "assets/shaders/french_fries.vert"
FRAGMENT_FRENCH_FRIES = "assets/shaders/french_fries.frag"
VERTEX_PLAYER = "assets/shaders/cake.vert"
FRAGMENT_PLAYER = "assets/shaders/cake.frag"